"""adding creator of a trip

Revision ID: 22afd3c28367
Revises: 732b8aa6ae74
Create Date: 2026-05-13 08:22:14.704851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22afd3c28367'
down_revision: Union[str, Sequence[str], None] = '732b8aa6ae74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('creator_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'trips', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_column('trips', 'creator_id')
    # ### end Alembic commands ###
