"""adding start datetime and end datetime

Revision ID: 6c0fab7fc561
Revises: 7be2b4ecf9ea
Create Date: 2026-06-14 10:37:45.903782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c0fab7fc561'
down_revision: Union[str, Sequence[str], None] = '7be2b4ecf9ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trips', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('trips', 'days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('trips', 'end_date')
    op.drop_column('trips', 'start_date')
    # ### end Alembic commands ###
