"""making creator_id non nullable

Revision ID: 77e773c73a5f
Revises: 22afd3c28367
Create Date: 2026-05-13 08:25:44.516921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e773c73a5f'
down_revision: Union[str, Sequence[str], None] = '22afd3c28367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'creator_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'creator_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
