"""adding status in user trip table

Revision ID: 7be2b4ecf9ea
Revises: 429db82bbb1c
Create Date: 2026-05-20 10:21:10.748847

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "7be2b4ecf9ea"
down_revision: Union[str, Sequence[str], None] = "429db82bbb1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

status_enum = postgresql.ENUM("PENDING", "REJECTED", "APPROVED", name="status_enum")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_trips", sa.Column("id", sa.UUID(), nullable=True))
    status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "user_trips",
        sa.Column(
            "status",
            sa.Enum("PENDING", "REJECTED", "APPROVED", name="status_enum"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_trips", "status")
    op.drop_column("user_trips", "id")
    status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
