"""renaming start and end date to be datetime

Revision ID: 8988323d0bbe
Revises: c43f0603133f
Create Date: 2026-06-14 11:11:09.418996

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8988323d0bbe"
down_revision: Union[str, Sequence[str], None] = "c43f0603133f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("trips", "start_date", new_column_name="start_datetime")
    op.alter_column("trips", "end_date", new_column_name="end_datetime")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("trips", "start_datetime", new_column_name="start_date")
    op.alter_column("trips", "end_datetime", new_column_name="end_date")
    # ### end Alembic commands ###
