"""adding description field in activity

Revision ID: b003aed18c5a
Revises: ece0e3142721
Create Date: 2026-06-15 08:38:07.480867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b003aed18c5a'
down_revision: Union[str, Sequence[str], None] = 'ece0e3142721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'description')
    # ### end Alembic commands ###
