"""adding trips table

Revision ID: b43bd765a9d1
Revises: 485be3c5eee1
Create Date: 2026-05-04 19:15:38.253549

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b43bd765a9d1"
down_revision: Union[str, Sequence[str], None] = "485be3c5eee1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

role_enum = postgresql.ENUM("ADMIN", "USER", "MANAGER", name="role_enum")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trips",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("destination", sa.String(length=120), nullable=False),
        sa.Column("days", sa.Integer(), nullable=True),
        sa.Column("budget", sa.Float(), nullable=True),
        sa.Column(
            "trip_style", sa.Enum("BUDGET", name="trip_style_enum"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("ADMIN", "MANAGER", "USER", name="role_enum"),
            nullable=False,
            server_default="USER",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    op.drop_table("trips")
    role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
