"""adding title and description in trip model

Revision ID: e5cb6bc4a06a
Revises: 8988323d0bbe
Create Date: 2026-06-14 13:23:47.682003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5cb6bc4a06a'
down_revision: Union[str, Sequence[str], None] = '8988323d0bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('trips', sa.Column('description', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'description')
    op.drop_column('trips', 'title')
    # ### end Alembic commands ###
