"""renaming itinerary_day to itinerary

Revision ID: ece0e3142721
Revises: 652cc2e3c00b
Create Date: 2026-06-14 21:16:36.720533

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ece0e3142721"
down_revision: Union[str, Sequence[str], None] = "652cc2e3c00b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("itinerary_days", "itineraries")
    op.alter_column("itineraries", "day_number", new_column_name="day")
    op.alter_column("activities", "itinerary_day_id", new_column_name="itinerary_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("itineraries", "itinerary_days")
    op.alter_column("itinerary_days", "day", new_column_name="day_number")
    op.alter_column("activities", "itinerary_id", new_column_name="itinerary_day_id")
    # ### end Alembic commands ###
